---
- box: ubuntu/groovy64
  group: ubuntu
  codename: groovy
  ip: 172.16.10.10
- box: ubuntu/focal64
  group: ubuntu
  codename: focal
  ip: 172.16.10.11
- box: ubuntu/bionic64
  group: ubuntu
  codename: bionic
  ip: 172.16.10.12
- box: ubuntu/xenial64
  group: ubuntu
  codename: xenial
  ip: 172.16.10.13

- box: debian/buster64
  group: debian
  codename: buster
  ip: 172.16.11.10
- box: debian/stretch64
  group: debian
  codename: stretch
  ip: 172.16.11.11
- box: geerlingguy/debian8
  group: debian
  codename: jessie
  ip: 172.16.11.12

- box: bento/centos-8.2
  group: centos
  codename: '8'
  ip: 172.16.12.10
- box: bento/centos-7.6
  group: centos
  codename: '7'
  ip: 172.16.12.11
- box: bento/centos-6.8
  group: centos
  codename: '6'
  ip: 172.16.12.12
