---
- box: ubuntu/groovy64
  group: ubuntu
  codename: groovy
  ip: 172.16.10.10
- box: bento/ubuntu-20.04
  group: ubuntu
  codename: focal
  ip: 172.16.10.11
- box: bento/ubuntu-18.04
  group: ubuntu
  codename: bionic
  ip: 172.16.10.12
- box: bento/ubuntu-16.04
  group: ubuntu
  codename: xenial
  ip: 172.16.10.13

- box: bento/debian-10
  group: debian
  codename: buster
  ip: 172.16.11.10
- box: bento/debian-9
  group: debian
  codename: stretch
  ip: 172.16.11.11
- box: bento/debian-8
  group: debian
  codename: jessie
  ip: 172.16.11.12

- box: bento/centos-8
  group: centos
  codename: '8'
  ip: 172.16.12.10
- box: bento/centos-7
  group: centos
  codename: '7'
  ip: 172.16.12.11
- box: bento/centos-6
  group: centos
  codename: '6'
  ip: 172.16.12.12

# - box: generic/rhel8
#   group: rhel
#   codename: '8'
#   ip: 172.16.13.10
# - box: roboxes/rhel7
#   group: rhel
#   codename: '7'
#   ip: 172.16.13.11
# - box: roboxes/rhel6
#   group: rhel
#   codename: '6'
#   ip: 172.16.13.12
