---
# role: audit_tools
# file: handlers/main.yml

- name: generate auditd
  command: augenrules

- name: restart auditd
  service:
    name: auditd
    state: restarted
# - name: run command
#   command: echo "hello world"

# - name: enable and restart service
#   service:
#     name:
#     state: restarted
#     enabled: true
