---
# role: base
# file: defaults/main.yml

# The role is disabled by default, so you do not get in trouble.
# Checked in tasks/main.yml which includes tasks.yml if enabled.
base_enabled: true

base_cache_seconds: 3600
base_daily_package_download: true
base_daily_package_command: "apt-get update && apt-get --assume-yes --download-only upgrade"

base_packages:
  [
    "apt-show-versions",
    "bind9utils",
    "build-essential",
    "curl",
    "git",
    "grep",
    "hwinfo",
    "linux-headers-{{ ansible_kernel }}",
    "net-tools",
    "openssl",
    "python3",
    "python3-pip",
    "python3-setuptools",
    "software-properties-common",
    "tar",
    "traceroute",
    "tzdata",
    "vim",
    "wget",
    "whois",
  ]

base_timezone: America/New_York

base_system_locale: "en_US.UTF-8"
base_system_language: "en_US.UTF-8"

base_swap_vm_swappiness: 1
base_swap_vm_vfs_cache_pressure: 50
base_swap_vm_hugepages: 20480
base_swap_swapfile_size: "{{ (ansible_memtotal_mb * 1.5) | int }}m"
