---
# role: audit_tools
# file: meta/main.yml

galaxy_info:
  role_name: audit_tools
  author: Stefan Crain
  description: Ansible role for setting up audit_tools
  company: ""

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: MIT

  min_ansible_version: 2.8

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  github_branch: master

  # platforms is a list of platforms, and each platform has a name and a list of versions.
  #
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - web
    - system
    - server
    - security
    - audit

  dependencies: []
