---
# role: audit_tools
# file: defaults/main.yml

# The role is disabled by default, so you do not get in trouble.
# Checked in tasks/main.yml which includes tasks.yml if enabled.
audit_tools_enabled: true
audit_tools_cache_seconds: 3600
audit_tools_packages: ["aide", "auditd", "debsums", "chkrootkit", "rkhunter"]
audit_tools_cron_frequency: daily

audit_tools_chkrootkit_rundaily: true
audit_tools_chkrootkit_rundaily_opts: "-q"
audit_tools_chkrootkit_diffmode: false
